apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: sparta-node-app-deploy
  namespace: default
  
spec:
  maxReplicas: 9
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sparta-node-app-deploy
  targetCPUUtilizationPercentage: 50

  # kubectl scale deploy sparta-node-app-deploy --replicas=5
  # kubectl autoscale deploy sparta-node-app-deploy --cpu-percent=50 --min=2 --max=9
   - https://v1-20.docs.kubernetes.io/docs/tutorials/stateless-application/guestbook/